# Generated by Django 4.2.5 on 2023-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0003_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('material_description', models.TextField()),
                ('stock_16_18', models.PositiveIntegerField()),
                ('stock_20_24', models.PositiveIntegerField()),
                ('stock_25_29', models.PositiveIntegerField()),
                ('stock_30_35', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_16_19', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
