# Generated by Django 4.2.5 on 2023-11-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0005_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='male',
            field=models.BooleanField(default=False),
        ),
    ]
