# Generated by Django 4.2.5 on 2023-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0008_remove_product_product_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(default='', upload_to='thumbnail/'),
        ),
    ]
