# Generated by Django 4.2.5 on 2023-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0011_bookcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
