# Generated by Django 4.2.5 on 2023-11-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0012_alter_product_total_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_1_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_16_19',
            new_name='price_4_12',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_16_18',
            new_name='stock_4_8',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_20_24',
            new_name='stock_9_12',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_25_29',
            new_name='stock_for_child_1_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_30_35',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FileField(default='', upload_to='profile/'),
        ),
    ]
