# Generated by Django 4.2.5 on 2023-11-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0014_sizestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_1_3',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_4_12',
            new_name='price_16_19',
        ),
    ]
