# Generated by Django 4.2.5 on 2023-11-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0016_bookcart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcart',
            name='size',
            field=models.CharField(default='1', max_length=5, null=True),
        ),
    ]
