# Generated by Django 4.2.5 on 2023-11-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0022_remove_shippingaddress_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
    ]
