# Generated by Django 4.2.5 on 2023-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0027_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
