# Generated by Django 4.2.6 on 2024-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0030_agentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Admin'), (3, 'Merchant'), (4, 'Agent')], null=True),
        ),
    ]
