# Generated by Django 4.2.6 on 2024-03-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0036_newarrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/product_returns/')),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products_received', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
