# Generated by Django 4.2.6 on 2024-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StepGuideApp', '0040_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out_for_delivery', 'Out for Delivery'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
